# Generated by Django 5.1.6 on 2025-02-21 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.program')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('benefciary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.beneficiary')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.plan')),
            ],
        ),
    ]
